### ISSUE TITLE
SAI headers uses in dash pipeline issue

### ISSUE THREAD

**Issue by kcudnik** [sonic-net/DASH#409]
dash pipeline is using SAI at pointer 52e7b42 (HEAD) Update PTF submodule

this commit does non exist in main SAI repo, latest compatible is d317fa9 (after v1.10.0) (commit comes from private repo https://github.com/reshmaintel/SAI.git)

dash API don't exist on v1.10.0 main repo, and are auto generated via dash pipeline in DASH SAI repo, and appended at sai_api_extensions_t struct and auto populates this struct as well as creating experimental/saiexperimentaldash*.h files

but dash api start exist on main SAI repo at v1.11.0, after commit f996068 Add DASH API (#1590)

which add new extra api:

```
git diff d317fa9 f996068  inc/sai.h
```

```c
diff --git a/inc/sai.h b/inc/sai.h
index 5e50a75..f788dce 100644
--- a/inc/sai.h
+++ b/inc/sai.h
@@ -74,6 +74,7 @@
 #include "saiisolationgroup.h"
 #include "saidebugcounter.h"
 #include "saimymac.h"
+#include "saigenericprogrammable.h"
 #include "saiversion.h"
 
 /**
@@ -138,6 +139,7 @@ typedef enum _sai_api_t
     SAI_API_SYSTEM_PORT      = 44, /**< sai_system_port_api_t */
     SAI_API_MY_MAC           = 45, /**< sai_my_mac_api_t */
     SAI_API_IPSEC            = 46, /**< sai_ipsec_api_t */
+    SAI_API_GENERIC_PROGRAMMABLE = 47, /**<sai_generic_programmable_t */
     SAI_API_MAX,                   /**< total number of APIs */
 } sai_api_t;
```

and shifts entire API and SAI_API_MAX, which will cause crash, since pointers for DASH api will not match, enums are shifted compared to main SAI repo at f996068 

**_i didn't dive deep enough, but not sure even if at that point both those apis are compatible with each other, whether dash api auto implemented in dash-pipeline at commit 52e7b42 are compatible with main repo SAI at commit f996068_**  it't not straight forward to  check that compatibility, also between those commits other stuff to SAI repo was added:

```
git diff d317fa9 f996068 --stat
```

```
 experimental/saiexperimentaldashacl.h                            |   310 +++
 experimental/saiexperimentaldashdirectionlookup.h                |   205 ++
 experimental/saiexperimentaldasheni.h                            |   565 +++++
 experimental/saiexperimentaldashinboundrouting.h                 |   241 ++
 experimental/saiexperimentaldashoutboundcatopa.h                 |   234 ++
 experimental/saiexperimentaldashoutboundrouting.h                |   253 ++
 experimental/saiexperimentaldashpavalidation.h                   |   212 ++
 experimental/saiexperimentaldashvip.h                            |   205 ++
 experimental/saiexperimentaldashvnet.h                           |   134 +
 experimental/saiextensions.h                                     |    27 +
 experimental/saitypesextensions.h                                |    22 +
 inc/sai.h                                                        |     2 +
 inc/saigenericprogrammable.h                                     |   155 ++
 inc/saihostif.h                                                  |     9 +
 inc/sainexthopgroup.h                                            |    13 +
 inc/saiobject.h                                                  |    49 +
 inc/saipolicer.h                                                 |     9 +
 inc/saiport.h                                                    |   101 +-
 inc/saistatus.h                                                  |     5 +
 inc/saiswitch.h                                                  |    42 +
 inc/saitypes.h                                                   |    55 +
 inc/saiversion.h                                                 |     2 +-
```

in other words since SYNCD is using internal main SAI repo commit to compile SYNCD, **_there is no common commit on main SAI and dash SAI repos which causes sonic/sairedis syncd and dash-pipeline to be INCOMPATTIBLE because of enum shifts and it cannot be run, it will cause crash immediately_** also using commit d317fa9 in sairedis repo, will cause syncd to be not aware of any DASH api since at this commit in main SAI redis repo, DASH api don't exist yet

the easiest way to fix this, please move SAI repo pointer inside dash-pipeline to some existing pointer on master branch, which contains DASH api, for example one of those:

```
e15cc85 (HEAD, origin/master, origin/HEAD) Tunnel Term Attributes validation fixed for all MP2P and MP2MP attributes (#1799)
ef4b8b4 DASH metering policies (#1819)
3ff228a (tag: v1.12.0) Updated major version (#1782)
f996068 Add DASH API (#1590)
```

or basically any commit after or f996068, and then generate DASH api using dash-pipeline (libsai.so) without modifying SAI/inc/\*.h and SAI/experimental/\*.h

then we will have a common commit on which we can ralay between DASH repo and sonic/sairedis repo for syncd compatibility and we will be able to make libsai.so lib working on sonic-sairedis repo for syncd purposes  

@lguohan FYI

the branch which we were testing on DASH repo was at commit 07464d0, which you can clearly see that it's using private repo

```
$ git diff origin/main 07464d0 .gitmodules
diff --git a/.gitmodules b/.gitmodules
index eee4f5e..0ced2e4 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,7 +1,7 @@
 [submodule "dash-pipeline/SAI/SAI"]
        path = dash-pipeline/SAI/SAI
-       url = https://github.com/opencomputeproject/SAI.git
-       branch = master
+       url = https://github.com/reshmaintel/SAI.git
+       branch = dash-ptf-ci
 [submodule "test/SAI-Challenger"]
        path = test/SAI-Challenger
        url = https://github.com/opencomputeproject/SAI-Challenger.git
```

since PTF tests only work on this branch, they don't work on origin/main branch, which points SAI repo to origin/master

**Comment by Pterosaur** [comment]
In the latest main branch of DASH, I find the SAI repo has been repointed to the public OCP's. Could it fix this issue?
![image](https://github.com/sonic-net/DASH/assets/18609639/43c04a0b-2969-4b3a-8ead-c8b463ad3882)

**Comment by kcudnik** [comment]
somehow i can't reproduce tests running any more on my machine i get some errors

```
git clone https://github.com/sonic-net/DASH.git
cd DASH
git co 07464d0 -b working_maybe # cleanup in dash testcases (return proper objects, fix remove command (#393)
git submodule update --init
cd dash-pipeline/

make clean
make all # this build fails :(
make run-switch # blocking command
make run-saithrift-server # blocking command 
make run-saithrift-ptftests #
make kill-all
```

```
 -L/usr/lib -Wl,-rpath=/usr/lib ./obj/sai_rpc_server.o ./obj/saiserver.o -o saiserver \
           ./obj/librpcserver.a -lthrift -lpthread -lsai  -L/lib/x86_64-linux-gnu -Wl,-rpath=/lib/x86_64-linux-gnu -lm -L/usr/local/lib/ -Wl,-rpath=/usr/local/lib -lpthread -lpiprotogrpc -lpiprotobuf -lprotobuf -lgrpc++ -lgrpc -lpiall -lpi_dummy -lpthread -labsl_synchronization -labsl_status -labsl_raw_hash_set -lgpr -lre2 -lssl -laddress_sorting
/usr/bin/thrift -o ./ --gen py -r ../../meta/sai.thrift
/usr/local/bin/ctypesgen --output-language=py32 -I/usr/include -I/usr/include/sai --include /usr/include/linux/limits.h /usr/include/sai/sai.h /usr/include/sai/saiacl.h /usr/include/sai/saibfd.h /usr/include/sai/saibridge.h /usr/include/sai/saibuffer.h /usr/include/sai/saicounter.h /usr/include/sai/saidebugcounter.h /usr/include/sai/saidtel.h /usr/include/sai/saiexperimentalbmtor.h /usr/include/sai/saiexperimentaldashacl.h /usr/include/sai/saiexperimentaldashdirectionlookup.h /usr/include/sai/saiexperimentaldasheni.h /usr/include/sai/saiexperimentaldashinboundrouting.h /usr/include/sai/saiexperimentaldashmeter.h /usr/include/sai/saiexperimentaldashoutboundcatopa.h /usr/include/sai/saiexperimentaldashoutboundrouting.h /usr/include/sai/saiexperimentaldashpavalidation.h /usr/include/sai/saiexperimentaldashtag.h /usr/include/sai/saiexperimentaldashvip.h /usr/include/sai/saiexperimentaldashvnet.h /usr/include/sai/saiextensions.h /usr/include/sai/saifdb.h /usr/include/sai/saihash.h /usr/include/sai/saihostif.h /usr/include/sai/saiipmc.h /usr/include/sai/saiipmcgroup.h /usr/include/sai/saiipsec.h /usr/include/sai/saiisolationgroup.h /usr/include/sai/sail2mc.h /usr/include/sai/sail2mcgroup.h /usr/include/sai/sailag.h /usr/include/sai/saimacsec.h /usr/include/sai/saimcastfdb.h /usr/include/sai/saimirror.h /usr/include/sai/saimpls.h /usr/include/sai/saimymac.h /usr/include/sai/sainat.h /usr/include/sai/saineighbor.h /usr/include/sai/sainexthop.h /usr/include/sai/sainexthopgroup.h /usr/include/sai/saiobject.h /usr/include/sai/saipolicer.h /usr/include/sai/saiport.h /usr/include/sai/saiqosmap.h /usr/include/sai/saiqueue.h /usr/include/sai/sairoute.h /usr/include/sai/sairouterinterface.h /usr/include/sai/sairpfgroup.h /usr/include/sai/saisamplepacket.h /usr/include/sai/saischeduler.h /usr/include/sai/saischedulergroup.h /usr/include/sai/saisrv6.h /usr/include/sai/saistatus.h /usr/include/sai/saistp.h /usr/include/sai/saiswitch.h /usr/include/sai/saiswitchextensions.h /usr/include/sai/saisystemport.h /usr/include/sai/saitam.h /usr/include/sai/saitunnel.h /usr/include/sai/saitypes.h /usr/include/sai/saitypesextensions.h /usr/include/sai/saiudf.h /usr/include/sai/saiversion.h /usr/include/sai/saivirtualrouter.h /usr/include/sai/saivlan.h /usr/include/sai/saiwred.h -o gen-py/sai/sai_headers.py
WARNING: No libraries specified
INFO: Status: Preprocessing /tmp/tmp8nxxeorh.h
INFO: Status: gcc -E -U __GNUC__ -dD -I"/usr/include" -I"/usr/include/sai" "-D__extension__=" "-D__const=const" "-D__asm__(x)=" "-D__asm(x)=" "-DCTYPESGEN=1" "/tmp/tmp8nxxeorh.h"
INFO: Status: Parsing /tmp/tmp8nxxeorh.h
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:281: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:308: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:315: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:321: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:330: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:331: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:339: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:397: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:406: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:433: Syntax error at '\n'
INFO: Status: Processing description list.
INFO: Status: Writing to gen-py/sai/sai_headers.py.
INFO: Status: Wrapping complete.
python3 setup.py sdist
/dash/dash-pipeline/SAI/SAI/test/saithriftv2/setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
running sdist
running check
warning: sdist: manifest template 'MANIFEST.in' does not exist (using default file list)

warning: sdist: standard file not found: should have one of README, README.txt, README.rst

writing manifest file 'MANIFEST'
creating saithrift-0.9
creating saithrift-0.9/gen-py
creating saithrift-0.9/gen-py/sai
making hard links in saithrift-0.9...
hard linking setup.py -> saithrift-0.9
hard linking gen-py/sai/__init__.py -> saithrift-0.9/gen-py/sai
hard linking gen-py/sai/constants.py -> saithrift-0.9/gen-py/sai
hard linking gen-py/sai/sai_headers.py -> saithrift-0.9/gen-py/sai
hard linking gen-py/sai/sai_rpc.py -> saithrift-0.9/gen-py/sai
hard linking gen-py/sai/ttypes.py -> saithrift-0.9/gen-py/sai
```

**Comment by kcudnik** [comment]
even on dash master, which is pointing to SAI master as well, there are some changes in attributes values for dash:

```
DASH/dash-pipeline/SAI/SAI $ git diff


diff --git a/experimental/saiexperimentaldashacl.h b/experimental/saiexperimentaldashacl.h
index 1a61133..d80761a 100644
--- a/experimental/saiexperimentaldashacl.h
+++ b/experimental/saiexperimentaldashacl.h
@@ -111,42 +111,76 @@ typedef enum _sai_dash_acl_rule_attr_t
     SAI_DASH_ACL_RULE_ATTR_DASH_ACL_GROUP_ID,

     /**
-     * @brief List matched key dip
+     * @brief Ternary matched key dst_tag
      *
-     * @type sai_ip_prefix_list_t
+     * @type sai_uint32_t
+     * @flags MANDATORY_ON_CREATE | CREATE_ONLY
+     */
+    SAI_DASH_ACL_RULE_ATTR_DST_TAG,
+
+    /**
+     * @brief Ternary matched mask dst_tag
+     *
+     * @type sai_uint32_t
+     * @flags MANDATORY_ON_CREATE | CREATE_ONLY
+     */
+    SAI_DASH_ACL_RULE_ATTR_DST_TAG_MASK,
+
+    /**
+     * @brief Ternary matched key src_tag
+     *
+     * @type sai_uint32_t
+     * @flags MANDATORY_ON_CREATE | CREATE_ONLY
+     */
+    SAI_DASH_ACL_RULE_ATTR_SRC_TAG,
+
+    /**
+     * @brief Ternary matched mask src_tag
+     *
+     * @type sai_uint32_t
+     * @flags MANDATORY_ON_CREATE | CREATE_ONLY
+     */
+    SAI_DASH_ACL_RULE_ATTR_SRC_TAG_MASK,
+
+    /**
+     * @brief Optional matched key dip
+     *
+     * @type sai_ip_address_t
      * @flags MANDATORY_ON_CREATE | CREATE_ONLY
      */
     SAI_DASH_ACL_RULE_ATTR_DIP,

     /**
-     * @brief List matched key sip
+     * @brief Optional matched key sip
      *
-     * @type sai_ip_prefix_list_t
+     * @type sai_ip_address_t
      * @flags MANDATORY_ON_CREATE | CREATE_ONLY
      */
     SAI_DASH_ACL_RULE_ATTR_SIP,

     /**
-     * @brief List matched key protocol
+     * @brief Optional matched key protocol
      *
-     * @type sai_u8_list_t
+     * @type sai_uint8_t
      * @flags MANDATORY_ON_CREATE | CREATE_ONLY
      */
     SAI_DASH_ACL_RULE_ATTR_PROTOCOL,

     /**
-     * @brief Range_list matched key src_port
+     * @brief Optional matched key src_port
      *
-     * @type sai_u16_range_list_t
+     * @type sai_uint16_t
      * @flags MANDATORY_ON_CREATE | CREATE_ONLY
+     * @isvlan false
      */
     SAI_DASH_ACL_RULE_ATTR_SRC_PORT,

     /**
-     * @brief Range_list matched key dst_port
+     * @brief Optional matched key dst_port
      *
-     * @type sai_u16_range_list_t
+     * @type sai_uint16_t
      * @flags MANDATORY_ON_CREATE | CREATE_ONLY
+     * @isvlan false
      */
     SAI_DASH_ACL_RULE_ATTR_DST_PORT,

@@ -171,15 +205,6 @@ typedef enum _sai_dash_acl_rule_attr_t
      */
     SAI_DASH_ACL_RULE_ATTR_PRIORITY,

-    /**
-     * @brief IP address family for resource accounting
-     *
-     * @type sai_ip_addr_family_t
-     * @flags READ_ONLY
-     * @isresourcetype true
-     */
-    SAI_DASH_ACL_RULE_ATTR_IP_ADDR_FAMILY,
-
     /**
      * @brief End of attributes
      */
diff --git a/experimental/saiexperimentaldasheni.h b/experimental/saiexperimentaldasheni.h
index 414cf15..d796604 100644
--- a/experimental/saiexperimentaldasheni.h
+++ b/experimental/saiexperimentaldasheni.h
@@ -161,6 +161,28 @@ typedef enum _sai_eni_attr_t
      */
     SAI_ENI_ATTR_VNET_ID,

+    /**
+     * @brief Action set_eni_attrs parameter V4_METER_POLICY_ID
+     *
+     * @type sai_object_id_t
+     * @flags CREATE_AND_SET
+     * @objects SAI_OBJECT_TYPE_METER_POLICY
+     * @allownull true
+     * @default SAI_NULL_OBJECT_ID
+     */
+    SAI_ENI_ATTR_V4_METER_POLICY_ID,
+
+    /**
+     * @brief Action set_eni_attrs parameter V6_METER_POLICY_ID
+     *
+     * @type sai_object_id_t
+     * @flags CREATE_AND_SET
+     * @objects SAI_OBJECT_TYPE_METER_POLICY
+     * @allownull true
+     * @default SAI_NULL_OBJECT_ID
+     */
+    SAI_ENI_ATTR_V6_METER_POLICY_ID,
+
+
     /**
      * @brief Action set_eni_attrs parameter INBOUND_V4_STAGE1_DASH_ACL_GROUP_ID
      *
diff --git a/experimental/saiexperimentaldashoutboundcatopa.h b/experimental/saiexperimentaldashoutboundcatopa.h
index b08dfb8..cec14a2 100644
--- a/experimental/saiexperimentaldashoutboundcatopa.h
+++ b/experimental/saiexperimentaldashoutboundcatopa.h
@@ -96,6 +96,25 @@ typedef enum _sai_outbound_ca_to_pa_entry_attr_t
      */
     SAI_OUTBOUND_CA_TO_PA_ENTRY_ATTR_USE_DST_VNET_VNI,

+    /**
+     * @brief Action set_tunnel_mapping parameter METER_CLASS
+     *
+     * @type sai_uint16_t
+     * @flags CREATE_AND_SET
+     * @isvlan false
+     * @default 0
+     */
+    SAI_OUTBOUND_CA_TO_PA_ENTRY_ATTR_METER_CLASS,
+
+    /**
+     * @brief Action set_tunnel_mapping parameter METER_CLASS_OVERRIDE
+     *
+     * @type bool
+     * @flags CREATE_AND_SET
+     * @default false
+     */
+    SAI_OUTBOUND_CA_TO_PA_ENTRY_ATTR_METER_CLASS_OVERRIDE,
+
     /**
      * @brief Attach a counter
      *
diff --git a/experimental/saiexperimentaldashoutboundrouting.h b/experimental/saiexperimentaldashoutboundrouting.h
index 6d2c41e..414445e 100644
--- a/experimental/saiexperimentaldashoutboundrouting.h
+++ b/experimental/saiexperimentaldashoutboundrouting.h
@@ -107,6 +107,27 @@ typedef enum _sai_outbound_routing_entry_attr_t
      */
     SAI_OUTBOUND_ROUTING_ENTRY_ATTR_DST_VNET_ID,

+    /**
+     * @brief Action route_vnet, route_vnet_direct, route_direct, route_service_tunnel parameter METER_POLICY_EN
+     *
+     * @type bool
+     * @flags CREATE_AND_SET
+     * @default false
+     * @validonly SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION == SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_VNET or SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION == SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_VNET_DIRECT or SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION == SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_DIRECT or SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION == SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_SERVICE_TUNNEL
+     */
+    SAI_OUTBOUND_ROUTING_ENTRY_ATTR_METER_POLICY_EN,
+
+    /**
+     * @brief Action route_vnet, route_vnet_direct, route_direct, route_service_tunnel parameter METER_CLASS
+     *
+     * @type sai_uint16_t
+     * @flags CREATE_AND_SET
+     * @isvlan false
+     * @default 0
+     * @validonly SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION == SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_VNET or SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION == SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_VNET_DIRECT or SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION == SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_DIRECT or SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION == SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_SERVICE_TUNNEL
+     */
+    SAI_OUTBOUND_ROUTING_ENTRY_ATTR_METER_CLASS,
+
     /**
      * @brief Action route_vnet_direct parameter OVERLAY_IP
     /**
      * @brief Action route_vnet_direct parameter OVERLAY_IP
      *
@@ -182,7 +203,7 @@ typedef enum _sai_outbound_routing_entry_attr_t
      *
      * @type sai_dash_encapsulation_t
      * @flags CREATE_AND_SET
-     * @default SAI_DASH_ENCAPSULATION_VXLAN
+     * @default SAI_DASH_ENCAPSULATION_INVALID
      * @validonly SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION == SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_SERVICE_TUNNEL
      */
     SAI_OUTBOUND_ROUTING_ENTRY_ATTR_DASH_ENCAPSULATION,
diff --git a/experimental/saiextensions.h b/experimental/saiextensions.h
index be05315..8fc9ef0 100644
--- a/experimental/saiextensions.h
+++ b/experimental/saiextensions.h
@@ -33,6 +33,8 @@
 #include "saiswitchextensions.h"

 /* new experimental object type includes */
+#include "saiexperimentaldashmeter.h"
+#include "saiexperimentaldashtag.h"
 #include "saiexperimentaldashvip.h"
 #include "saiexperimentaldashpavalidation.h"
 #include "saiexperimentaldashvnet.h"
@@ -73,6 +75,10 @@ typedef enum _sai_api_extensions_t

     SAI_API_DASH_VIP,

+    SAI_API_DASH_TAG,
+
+    SAI_API_DASH_METER,
+
     /* Add new experimental APIs above this line */

     SAI_API_EXTENSIONS_RANGE_END
diff --git a/experimental/saitypesextensions.h b/experimental/saitypesextensions.h
index b6a4e12..e9f00cb 100644
--- a/experimental/saitypesextensions.h
+++ b/experimental/saitypesextensions.h
@@ -64,6 +64,16 @@ typedef enum _sai_object_type_extensions_t

     SAI_OBJECT_TYPE_VIP_ENTRY,

+    SAI_OBJECT_TYPE_DST_TAG_ENTRY,
+
+    SAI_OBJECT_TYPE_SRC_TAG_ENTRY,
+
+    SAI_OBJECT_TYPE_METER_BUCKET,
+
+    SAI_OBJECT_TYPE_METER_POLICY,
+
+    SAI_OBJECT_TYPE_METER_RULE,
+
     /* Add new experimental object types above this line */

     SAI_OBJECT_TYPE_EXTENSIONS_RANGE_END
diff --git a/inc/saiobject.h b/inc/saiobject.h
index 8ee253a..37aecef 100644
--- a/inc/saiobject.h
+++ b/inc/saiobject.h
@@ -37,6 +37,17 @@
 #include <saisrv6.h>

 /* new experimental object type includes */
+#include "../experimental/saiexperimentaldashvip.h"
+#include "../experimental/saiexperimentaldashpavalidation.h"
+#include "../experimental/saiexperimentaldashvnet.h"
+#include "../experimental/saiexperimentaldashoutboundrouting.h"
+#include "../experimental/saiexperimentaldashoutboundcatopa.h"
+#include "../experimental/saiexperimentaldashmeter.h"
+#include "../experimental/saiexperimentaldashinboundrouting.h"
+#include "../experimental/saiexperimentaldasheni.h"
+#include "../experimental/saiexperimentaldashtag.h"
+#include "../experimental/saiexperimentaldashdirectionlookup.h"
+#include "../experimental/saiexperimentaldashacl.h"
 #include <saiexperimentaldashvip.h>
 #include <saiexperimentaldashpavalidation.h>
 #include <saiexperimentaldashvnet.h>
@@ -114,6 +125,12 @@ typedef union _sai_object_key_entry_t
     /** @validonly object_type == SAI_OBJECT_TYPE_VIP_ENTRY */
     sai_vip_entry_t vip_entry;

+    /** @validonly object_type == SAI_OBJECT_TYPE_DST_TAG_ENTRY */
+    sai_dst_tag_entry_t dst_tag_entry;
+
+    /** @validonly object_type == SAI_OBJECT_TYPE_SRC_TAG_ENTRY */
+    sai_src_tag_entry_t src_tag_entry;
+
     /* Add new experimental entries above this line */

 } sai_object_key_entry_t;
```

as you can see, many new object  types are added on SAI master, many object changes it actual attribute value type which is breaking change, many new attributes are introduced inside attr list and some are actually removed

those changes are not compatible with SAI master, and it will lead to crash when using with sairedis syncd

**Comment by kcudnik** [comment]
and make run-saithrift-ptftests, fails on master :( @Pterosaur let's have another session when you are available to try to fix this, im not familiar with those test deep enough to fix this on my own

**Comment by kcudnik** [comment]
Ok, seems like errors:
```
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:281: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:308: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:315: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:321: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:330: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:331: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:339: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:397: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:406: Syntax error at '\n'
ERROR: /usr/include/x86_64-linux-gnu/sys/cdefs.h:433: Syntax error at '\n'
INFO: Status: Processing description list.
```

are part of the compilation, line
```
g++ -I/usr/include/sai -I. -std=c++11 -O0 -ggdb -c gen-cpp/sai_rpc.cpp -o obj/sai_rpc.o  -I../../meta
```

compiles for a long time, and it needs to be executed 3 times on branch 07464d0

but main problem with headers incompatibility still remains

**Comment by kcudnik** [comment]
some build info for sairedis inside bmv2 docker:

```
# sonic

# DASH/dash-pipeline/SAI/SAI must be set manually to commit where syndc is pointing (currently origin/v1.12)
# this must be done via modify DASH/dash-pipeline/Makefile to checkout origin/v1.12 after sai-clean


#205 sai-clean: SAI/SAI libsai-clean saithrift-server-clean
#206     @echo "Restoring SAI subdirectories to baseline..."
#207     rm -rf SAI/SAI/inc SAI/SAI/experimental SAI/SAI/meta
#208     cd SAI/SAI && git checkout -- inc experimental meta
#209     cd SAI/SAI && git checkout origin/v1.12                # <<<

# dash tag and dash meter must be removed in order to compile syncd, since it's source code is not supporting that 


docker run \
    -v /home/kcudnik/dash2/DASH/dash-pipeline/bmv2/:/bmv2 \
    -v /home/kcudnik/dash2/DASH/dash-pipeline/SAI:/SAI \
    --network=host \
    --rm \
    -dit \
    -w /SAI/lib \
    --name build_libsai-sonic \
    -u root \
    sonicdash.azurecr.io/dash-bmv2-bldr:beeeda3f7ae \
    bash

alias log='git --no-pager log --graph --oneline --decorate --date=relative --all -n 20'

cd
apt-get update
apt-get install -y vim git
apt-get install -y libhiredis-dev libyang-dev
apt-get install -y libhiredis0.14 libyang0.16
apt-get install -y google-mock libgmock-dev
apt-get install -y libnl-3-dev libnl-genl-3-dev libnl-route-3-dev libnl-nf-3-dev
apt-get install -y libzmq5 libzmq3-dev
apt-get install -y swig4.0
apt-get install -y python3-dev
apt-get install -y uuid-dev
apt-get install -y autoconf-archive
apt-get install -y doxygen
apt-get install -y graphviz
apt-get install -y aspell-en


git clone https://github.com/sonic-net/sonic-swss-common.git

cd sonic-swss-common

sed -ie '/pyext.Makefile.am/d' Makefile.am
sed -ie '/tests.Makefile.am/d' Makefile.am

./autogen
./configure
make
make install
mkdir /usr/include/swss
cp -u common/*h /usr/include/swss/
cp -u common/*hpp /usr/include/swss/

cd

git clone https://github.com/Azure/sonic-sairedis.git

cd sonic-sairedis
# git submodule update --init
# adjust SAI pointer 

cp -r /SAI/SAI/inc /SAI/SAI/experimental /SAI/SAI/meta SAI/
cp -vu /SAI/lib/libsai.so /usr/local/lib/

perl -i.bak -pe 's/pyext.+Makefile//' configure.ac
perl -i.bak -pe 's/pyext//' Makefile.am
sed -ie '/unittest/d' configure.ac

./autogen
./configure --enable-python2=no
```

syncd needs updated branch:

```
https://github.com/kcudnik/sonic-sairedis/tree/tagmeter
```

**Comment by vincent-xs** [comment]
Kamil.

there is an outstanding issue I filed in DASH for ACL rule (https://github.com/sonic-net/DASH/issues/360). it's my belief the generated SAI API for ACL rule is improper. 
I wonder if that should be addressed before an actual export to main branch (which I believe is what you are doing).

**Comment by kcudnik** [comment]
> Kamil.
> 
> there is an outstanding issue I filed in DASH for ACL rule (#360). it's my belief the generated SAI API for ACL rule is improper. I wonder if that should be addressed before an actual export to main branch (which I believe is what you are doing).

yes im aware that there is issue at this stage, not sure how we can proceed with this, as im aware bmv2 needs to be fixed to support ip address lists

**Comment by chrispsommers** [comment]
@kcudnik I'm not sure where things stand on this, is it still an issue? Do we need to assign or reassign help?

**Comment by kcudnik** [comment]
i think this is not and issue any more, since we moved pointers on SAI, there are some differences because of that bmv2 list/ip_address limitation in dash acl, but other thinks are fine now

**Comment by KrisNey-MSFT** [comment]
Per 9/27/2023 DASH Community Call, the main issue is resolved however there is still a small discrepancy 
@kcudnik - ok to close?  
Thank you, Kristina

**Comment by kcudnik** [comment]
Yes, issue with supporting tables still exists but main issue resolved I think we can close this
